config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'genres/index'
    get 'genres/:id/edit' => 'genres#edit'
    post 'genres/:id/edit'=> 'genres#edit'
    
    post 'genres'=>'genres#create'
    patch 'genres/:id'=>'genres#update', as: 'update_genre'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit]
    resources :orders, only: [:show,:update]
     resources :order_details, only: [:update]
    patch 'customer/:id'=>'customers#update', as: 'update_customer'
    get 'items/new'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    get 'items/:id/edit/'=> 'items#edit', as: 'items_edit'
    post 'items'=>'items#create'
    patch 'items/:id'=>'items#update', as: 'update_item'
    get 'orders/:id'=> 'orders#show', as: 'show_order'
  
    
  end
  get 'customers/my_page' => 'public/customers#show'
  get 'customers/edit'=> 'public/customers#edit'
  patch 'customers'=>'public/customers#update'
  get 'unsubscribe'=> 'public/customers#unsubscribe'
  patch 'withdrow'=>'public/customers#withdrow'
  patch 'cart_items/:id'=>'public/cart_items#update', as: 'update_cart_items'
  post 'orders'=> 'public/orders#create'
  patch 'orders/:id'=> 'admin/orders#update', as: 'update_order'
  namespace :public do
   
    get 'orders'=> 'orders#index'
    get 'orders/new'=> 'orders#new'
    get 'orders/complete'=> 'orders#complete'
    get 'orders/:id'=> 'orders#show'
    post 'orders/confirm'=> 'orders#confirm'

    get 'cart_items/index'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post '/addresses'=>'addresses#create',as: 'create_addresses'
    delete 'addresses/:id'=>'addresses#destroy', as: 'destroy_addresses'
    patch  'addresses/:id'=>'addresses#update', as: 'update_addresses'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    post '/cart_items'=>'cart_items#create'
    delete 'cart_items/:id'=>'cart_items#destroy', as: 'destroy_cart_items'
    delete 'destroy_all'=>'cart_items#destroy_all'
 
    
    get 'homes/top'
    get 'homes/about'
  end
  
  namespace :admin do
    get 'homes/top'
  end


 devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
 
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root 'admin/homes#top'
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_details
    def with_tax_price
        (price * 1.1).floor
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item=Item.new
    @genre_name=Genre.all
  end

  def index
    @items=Item.page(params[:page])
    @genre=Genre.all

  end

  def show
     @item = Item.find(params[:id])  
  end

  def edit
    @item = Item.find(params[:id]) 
    @genre_name=Genre.all
  end
  def create
    item = Item.new(item_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    item.save
    # 4. トップ画面へリダイレクト
    redirect_to admin_items_show_path(item.id)
  end
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_show_path(item.id) 
  end
  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    <div class="row">
        <div class="col-md-8">
          <h1>編集画面</h1>
          <%= form_with model: @item, url: admin_update_item_path do |f| %>
          <ul>
              <label>画像</label>
              <label><%= f.file_field :image, accept: "image/*" %></label>
          </ul>
          <ul>
              <label>名前</label>
              <label><%= f.text_field :name%></label>
          </ul>
          <ul>
              <label>紹介</label>
              <label><%= f.text_field :introduction %></label>
          </ul>
          <ul>
              <label>説明</label>
              <label><%= f.text_area :caption %></label>
          </ul>
          <ul>
              <label>ジャンル</label>
              <label><%= f.collection_select :genre_id,@genre_name, :id, :name %></label>
          </ul>
          <ul>
              <label>価格</label>
              <label><%= f.text_field :price %></label>
          </ul>  
          <ul>
            
              <div class="done">
                <%= f.label :販売ステータス %>
                <label>
                  <%= f.radio_button :is_active, true %>
                  <%= f.label :is_active, '販売中', value: true %>
                </label>
                <label>
                  <%= f.radio_button :is_active, false %>
                  <%= f.label :is_active, '販売停止中', value: false %>
                </label>
              </div>
              <%= f.submit '新規投稿', class: 'btn-success' %>
          </ul>
          
          <% end %>
    </div>
  </div>
</main>

app/views/admin/items/index.html.erb
    <main>
        <div class="container px5 px-mx-0">
          <div class="row">
          <div class="col-md-4">
                <h2>商品一覧</h2>
              </div>
          <div class="col-md-8">
                <div class="float-right">
                    <%=link_to admin_items_new_path, :method => :get do %>
                        <i class="fa-solid fa-gear"></i>
                    <%end%>
                </div>
          </div>
          </div>
                <table class="table table-striped">
                    <tr>
                        <td>id</td>
                        <td>名前</td>
                        <td>販売価格</td>
                        <td>ジャンル</td>
                        <td>販売ステータス</td>
                    </tr>
                <% @items.each do |item| %>
                
                    <tr>
                        <td><%=item.id%></td>
                        <td><%=link_to item.name,admin_items_show_path(item.id)%></td>
                        <td><%=item.price%></td>
                        <td><%=item.genre.name%></td>
                        <%if item.is_active == true%>
                            <td>販売中</td>
                        <%else%>
                            <td>販売停止</td>
                        <%end%>
                        
                    </tr>
                
                   
                <%end%>
                
                </table>
                
                <%= paginate @items %>
            
          </div>
        </div>
    </main>
</html>
 

app/views/admin/items/new.html.erb
 <div class="container"> 
     <h1>商品新規登録</h1>
    <div class="row">
      
      <%= form_with model: @item, url: admin_items_path  do |f| %>
        <ul>
          <label>画像</label>
            <%= f.file_field :image, accept: "image/*" %>
        </ul>
        <ul>
          <label>名前</label>
            <%= f.text_field :name%>
        </ul>
        
        <ul>
          <label>説明</label>
            <%= f.text_area :introduction %>
        </ul>
        <ul>
          
          <label>ジャンル</label>
          
            <%= f.collection_select :genre_id,@genre_name, :id, :name %>
        </ul>
        <ul>
          <label>価格</label>
            <%= f.text_field :price %>
        </ul>
        <ul>
          
            <div class="done">
            <label>販売ステータス</label>
            <label>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, '販売中', value: true %>
            </label>
            <label>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, '販売停止中', value: false %>
            </label>
          </div>
          <%= f.submit '投稿',class: 'btn-success' %>
        </ul>
      
      <% end %>
    </div>
</div>

app/views/admin/items/show.html.erb
<main>
    <div class="container">
        <h1>商品詳細</h1>
      <div class="row">
            
            <div class="col-md-4">
            
                <ul>
                
                    <% if @item.image.attached? %>
                        <label><%= image_tag @item.image, size: "100x100" %></label>
                    <% else %>
                        <label><%= image_tag 'no_image', size: "100x100" %></label>
                    <% end %>
                    
                </ul>
            </div>
            <div class="col-md-8">
                <ul>
                    <label>商品名</label>
                    <label><%=@item.name%></label>
                </ul>
                <ul>
                    <label>商品説明</label>
                    <label><%=@item.introduction%></label>
                </ul>
                <ul>
                    <label>ジャンル</label>
                    <label><%=@item.genre.name%></label>
                </ul>
                <ul>
                    <label>税込価格</label>
                    <label><%=@item.price%></label>
                </ul>
                <ul>
                    <label>販売ステータス</label>
                    <%if @item.is_active == true%>
                            <label>販売中</label>
                        <%else%>
                            <label>販売停止</label>
                        <%end%>
                </ul>
                <ul>
                    <%=link_to '編集',admin_items_edit_path,class: 'btn-success'%>
                </ul>
            </div>
        </div>
    </div>
</main>