config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'genres/index'
    get 'genres/:id/edit' => 'genres#edit'
    post 'genres/:id/edit'=> 'genres#edit'
    
    post 'genres'=>'genres#create'
    patch 'genres/:id'=>'genres#update', as: 'update_genre'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit]
    resources :orders, only: [:show,:update]
     resources :order_details, only: [:update]
    patch 'customer/:id'=>'customers#update', as: 'update_customer'
    get 'items/new'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    get 'items/:id/edit/'=> 'items#edit', as: 'items_edit'
    post 'items'=>'items#create'
    patch 'items/:id'=>'items#update', as: 'update_item'
    get 'orders/:id'=> 'orders#show', as: 'show_order'
  
    
  end
  get 'customers/my_page' => 'public/customers#show'
  get 'customers/edit'=> 'public/customers#edit'
  patch 'customers'=>'public/customers#update'
  get 'unsubscribe'=> 'public/customers#unsubscribe'
  patch 'withdrow'=>'public/customers#withdrow'
  patch 'cart_items/:id'=>'public/cart_items#update', as: 'update_cart_items'
  post 'orders'=> 'public/orders#create'
  patch 'orders/:id'=> 'admin/orders#update', as: 'update_order'
  namespace :public do
   
    get 'orders'=> 'orders#index'
    get 'orders/new'=> 'orders#new'
    get 'orders/complete'=> 'orders#complete'
    get 'orders/:id'=> 'orders#show'
    post 'orders/confirm'=> 'orders#confirm'

    get 'cart_items/index'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post '/addresses'=>'addresses#create',as: 'create_addresses'
    delete 'addresses/:id'=>'addresses#destroy', as: 'destroy_addresses'
    patch  'addresses/:id'=>'addresses#update', as: 'update_addresses'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    post '/cart_items'=>'cart_items#create'
    delete 'cart_items/:id'=>'cart_items#destroy', as: 'destroy_cart_items'
    delete 'destroy_all'=>'cart_items#destroy_all'
 
    
    get 'homes/top'
    get 'homes/about'
  end
  
  namespace :admin do
    get 'homes/top'
  end


 devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
 
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root 'admin/homes#top'
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  def full_name
    self.first_name + self.last_name
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    def index
        @customers=Customer.page(params[:page])
       
        
    end
    def show
        @customer=Customer.find(params[:id])
        
    end
    def edit
         @customer=Customer.find(params[:id])
    end
    def update
        customer=Customer.find(params[:id])
        if customer.update(customer_params)
            redirect_to admin_customer_path(customer.id) 
        else
            render :new
        end
    end
    private
    def customer_params
        params.require(:customer).permit(:last_name, :first_name, :first_name_kana, :last_name_kana, :first_name_kana, :last_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main>
<h1><%=@customer.first_name+@customer.last_name%>さんの会員情報編集</h1>
    <table>
    <%= form_with model: @customer, url:  admin_update_customer_path(@customer.id) do |f| %>
    <tr>
        <div class="form-group">
            <td>会員ID</td>
            <td><%=@customer.id%></td>
        </div>
    </tr>
    <tr>
        <div class="form-group">
            <td>氏名</td>
            <td>
                <%= f.text_field :first_name%>
                <%= f.text_field :last_name%>
            </td>
        </div>
    </tr>
    <tr>
        <div class="form-group">
            <td>フリガナ</td>
            <td>
                <%= f.text_field :first_name_kana%>
                <%= f.text_field :last_name_kana%>
            </td>
        </div>
    </tr>
    <tr>
        <td>郵便番号</td>
        <td><%= f.text_field :postal_code%></td>
    </tr>
    <tr>
        <td>住所</td>
        <td><%= f.text_field :address%></td>
    </tr>
    <tr>
        <td>メールアドレス </td>
        <td><%= f.text_field :email%></td>
    </tr>
        
    
        
    <tr>
        <td>会員ステータス</td>
        <td>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_active, '退会', value: true %>
        </td> 
        <td>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_active, '有効', value: false %>
        </td>
          
    </tr>
    <tr>
        <td><%= f.submit '編集を保存',class: 'btn-success' %></td>
    </tr>
    <%end%>
    </table>
</main>

app/views/admin/customers/index.html.erb
<main>
    <div class="container">
      <div class="row">
        <h1>会員一覧</h1>
        <table class="table table-striped">
            <tr>
                <td>会員ナンバー</td>
                <td>氏名</td>
                <td>メールアドレス</td>
                <td>ステータス</td>
            </tr>
        <%@customers.each do |customer|%>
            <tr>
                <td><%=customer.id%></td>
                <td><%=link_to customer.first_name+customer.last_name, admin_customer_path(customer.id)%></td>
                <td><%=customer.email%></td>
                <%if customer.is_deleted==false%>
                    <td>
                          <font color="green"><%="有効"%></font>
                    </td>
                <%else%>
                    <td>
                        <font color="red"><%="退会"%></font>
                    </td>
                <%end%>
            </tr>
        <%end%>
        </table>
        <%= paginate @customers %>
      </div>
    </div>
</main>

app/views/admin/customers/show.html.erb
<main>
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h1>会員詳細</h1>
                <ul>
                    <label>会員ID</label>
                    <%=@customer.id%>
                </ul>
                <ul>
                    <label>氏名</label>
                    <%=@customer.first_name + @customer.last_name%>
                </ul>
                <ul>
                    <label>フリガナ</label>
                    <%=@customer.first_name_kana + @customer.last_name_kana%>
                </ul>
                <ul>
                    <label>郵便番号</label>
                    <%=@customer.postal_code%>
                </ul>
                <ul>
                    <label>住所</label>
                    <%=@customer.address%>
                </ul>
                <ul>
                    <label>電話番号</label>
                    <%=@customer.telephone_number%>
                </ul>
                <ul>
                    <label>メールアドレス</label>
                    <%=@customer.email%>
                </ul>
                <ul>
                    <label>会員ステータス</label>
                    <%if @customer.is_deleted==false%>
                        <td>
                            <font color="green"><%="有効"%></font>
                        </td>
                    <%else%>
                        <td>
                            <font color="red"><%="退会"%></font>
                        </td>
                    <%end%>
                </ul>
                <ul>
                    <label><%= link_to "編集する",  edit_admin_customer_path(@customer.id) , method: :get, class: "btn-success" %></label>
                    <label><%= link_to "注文一覧を見る",  admin_homes_top_path, class: "btn-primary"%></label>
                </ul>
            </div>
        </div>
    </div>
</main>