config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'genres/index'
    get 'genres/:id/edit' => 'genres#edit'
    post 'genres/:id/edit'=> 'genres#edit'
    
    post 'genres'=>'genres#create'
    patch 'genres/:id'=>'genres#update', as: 'update_genre'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit]
    resources :orders, only: [:show,:update]
     resources :order_details, only: [:update]
    patch 'customer/:id'=>'customers#update', as: 'update_customer'
    get 'items/new'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    get 'items/:id/edit/'=> 'items#edit', as: 'items_edit'
    post 'items'=>'items#create'
    patch 'items/:id'=>'items#update', as: 'update_item'
    get 'orders/:id'=> 'orders#show', as: 'show_order'
  
    
  end
  get 'customers/my_page' => 'public/customers#show'
  get 'customers/edit'=> 'public/customers#edit'
  patch 'customers'=>'public/customers#update'
  get 'unsubscribe'=> 'public/customers#unsubscribe'
  patch 'withdrow'=>'public/customers#withdrow'
  patch 'cart_items/:id'=>'public/cart_items#update', as: 'update_cart_items'
  post 'orders'=> 'public/orders#create'
  patch 'orders/:id'=> 'admin/orders#update', as: 'update_order'
  namespace :public do
   
    get 'orders'=> 'orders#index'
    get 'orders/new'=> 'orders#new'
    get 'orders/complete'=> 'orders#complete'
    get 'orders/:id'=> 'orders#show'
    post 'orders/confirm'=> 'orders#confirm'

    get 'cart_items/index'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post '/addresses'=>'addresses#create',as: 'create_addresses'
    delete 'addresses/:id'=>'addresses#destroy', as: 'destroy_addresses'
    patch  'addresses/:id'=>'addresses#update', as: 'update_addresses'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    post '/cart_items'=>'cart_items#create'
    delete 'cart_items/:id'=>'cart_items#destroy', as: 'destroy_cart_items'
    delete 'destroy_all'=>'cart_items#destroy_all'
 
    
    get 'homes/top'
    get 'homes/about'
  end
  
  namespace :admin do
    get 'homes/top'
  end


 devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
 
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root 'admin/homes#top'
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre= Genre.find(params[:id])
  end
  def create
      genre = Genre.new(genre_params)
      # 3. データをデータベースに保存するためのsaveメソッド実行
      genre.save
      # 4. トップ画面へリダイレクト
      redirect_to admin_genres_index_path
  end
  def update
    genre = Genre.find(params[:id])
    genre.update(genre1_params)
    redirect_to admin_genres_index_path  
  end
  private
    # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
  def genre1_params
    params.permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @genres , url: admin_update_genre_path(@genre.id), method: :patch do |f| %>
  <label for="inputName">ジャンル名</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder: @genre.name%>
  <%= f.submit '変更を保存' ,class: 'btn-success' %>
<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>
<%= form_with model: @genre, url: admin_genres_path  do |f| %>
<label>名前</label>
     <%= f.text_field :name%>
     <%= f.submit '新規投稿' ,class: 'btn-success' %>
<%end%>
<div class="container">  <!-- この行を追加 -->
  <div class="row">      <!-- この行を追加 -->
    <div class="col-lg-8">  
        <table class="table table-striped">
            <td>ジャンル
                <% @genres.each do |genre| %>
                
                    <ul><%= genre.name %>
                    <%= link_to "プロフィール編集",admin_path(genre.id),class: 'btn-success'%></ul>
                    <ul></ul>
                
                <%end%>
            </td>
        
    
         
    
        </table>
    </div>
  </div> 
</div>  