config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'genres/index'
    get 'genres/:id/edit' => 'genres#edit'
    post 'genres/:id/edit'=> 'genres#edit'
    
    post 'genres'=>'genres#create'
    patch 'genres/:id'=>'genres#update', as: 'update_genre'
  end
  namespace :admin do
    resources :customers, only: [:index, :show, :edit]
    resources :orders, only: [:show,:update]
     resources :order_details, only: [:update]
    patch 'customer/:id'=>'customers#update', as: 'update_customer'
    get 'items/new'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    get 'items/:id/edit/'=> 'items#edit', as: 'items_edit'
    post 'items'=>'items#create'
    patch 'items/:id'=>'items#update', as: 'update_item'
    get 'orders/:id'=> 'orders#show', as: 'show_order'
  
    
  end
  get 'customers/my_page' => 'public/customers#show'
  get 'customers/edit'=> 'public/customers#edit'
  patch 'customers'=>'public/customers#update'
  get 'unsubscribe'=> 'public/customers#unsubscribe'
  patch 'withdrow'=>'public/customers#withdrow'
  patch 'cart_items/:id'=>'public/cart_items#update', as: 'update_cart_items'
  post 'orders'=> 'public/orders#create'
  patch 'orders/:id'=> 'admin/orders#update', as: 'update_order'
  namespace :public do
   
    get 'orders'=> 'orders#index'
    get 'orders/new'=> 'orders#new'
    get 'orders/complete'=> 'orders#complete'
    get 'orders/:id'=> 'orders#show'
    post 'orders/confirm'=> 'orders#confirm'

    get 'cart_items/index'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post '/addresses'=>'addresses#create',as: 'create_addresses'
    delete 'addresses/:id'=>'addresses#destroy', as: 'destroy_addresses'
    patch  'addresses/:id'=>'addresses#update', as: 'update_addresses'
    get 'items/index'
    get 'items/:id'=> 'items#show', as: 'items_show'
    post '/cart_items'=>'cart_items#create'
    delete 'cart_items/:id'=>'cart_items#destroy', as: 'destroy_cart_items'
    delete 'destroy_all'=>'cart_items#destroy_all'
 
    
    get 'homes/top'
    get 'homes/about'
  end
  
  namespace :admin do
    get 'homes/top'
  end


 devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
 
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root 'admin/homes#top'
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def address_display
        '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    def subtotal
        item.with_tax_price * amount
    end
    def self.cart_items_total_price(cart_items)
        array=[]
        cart_items.each do |cart_item|
            array << cart_item.item.price*cart_item.amount
        end
    return (array.sum*1.1).floor
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  def full_name
    self.first_name + self.last_name
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_details
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status:  { wait: 0, confirmation: 1 , making: 2 , prepare: 3 , sent: 4  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
     belongs_to :order, dependent: :destroy
     belongs_to :item, dependent: :destroy
     enum making_status:  { impossible: 0, wait: 1 , making: 2 , complete: 3 }
     
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre=Genre.new
    @genres=Genre.all
  end

  def edit
    @genre= Genre.find(params[:id])
  end
  def create
      genre = Genre.new(genre_params)
      # 3. データをデータベースに保存するためのsaveメソッド実行
      genre.save
      # 4. トップ画面へリダイレクト
      redirect_to admin_genres_index_path
  end
  def update
    genre = Genre.find(params[:id])
    genre.update(genre1_params)
    redirect_to admin_genres_index_path  
  end
  private
    # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
  def genre1_params
    params.permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!, except: [:top]
  def top
    @orders=Order.page(params[:page])
    @order_details=OrderDetail.all
    @total_amount=0
    @customers=Customer.all
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item=Item.new
    @genre_name=Genre.all
  end

  def index
    @items=Item.page(params[:page])
    @genre=Genre.all

  end

  def show
     @item = Item.find(params[:id])  
  end

  def edit
    @item = Item.find(params[:id]) 
    @genre_name=Genre.all
  end
  def create
    item = Item.new(item_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    item.save
    # 4. トップ画面へリダイレクト
    redirect_to admin_items_show_path(item.id)
  end
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_show_path(item.id) 
  end
  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
            protect_from_forgery with: :exception

                   
            before_action :configure_permitted_parameters, if: :devise_controller?

            
            
            def after_sign_in_path_for(resource)
                case resource
                  when Customer
                    public_homes_top_path
                  when Admin
                    admin_homes_top_path
                end
            end
           
            private

            def configure_permitted_parameters

              devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
            end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagano12Cake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= link_to "Logo", public_homes_top_path, class: 'nav-link text-dark' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '商品一覧', public_items_index_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'カート一覧', public_cart_items_index_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', customers_my_page_path, class: 'nav-link text-dark' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '商品一覧', admin_items_index_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '注文一覧', admin_homes_top_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ジャンル一覧', admin_genres_index_path, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            
            <li class="nav-item">
              <%= link_to "ログイン",  new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "About",  public_homes_about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '商品一覧', public_items_index_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </header>

  

  <body>
    <%= yield %>
  </body>
  <footer class="bg-dark text-white pt-5 pb-4">
    <div class="container">
        <div class="row no-gutters">
        </div>
    </div>
  </footer>
    
</html>